name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5
      run: |
        echo "ruby-2.5.1" > ~/.ruby-version
    - name: Build and test with Rake
      run: |
        echo ruby --version
        sudo gem install bundler -v 1.17.2
        bundle install --jobs 4 --retry 3
        bundle exec rake
